"""Config package -- re-exports schema, loader, and errors for convenient imports."""

from m365_brain.config.errors import ConfigError
from m365_brain.config.loader import load_config
from m365_brain.config.schema import (
    AuthConfig,
    AzureBlobStorageConfig,
    CalendarExtractorConfig,
    Config,
    ContactsExtractorConfig,
    ConvertersConfig,
    DirectoryExtractorConfig,
    EmailExtractorConfig,
    ExplicitChannel,
    ExtractionConfig,
    ExtractorsConfig,
    GraphConfig,
    LocalStorageConfig,
    MailboxConfig,
    MediaConfig,
    OneDriveExtractorConfig,
    ServiceConfig,
    SharePointExtractorConfig,
    StateConfig,
    StorageConfig,
    TeamsChannelsExtractorConfig,
    TeamsChatsExtractorConfig,
    WebConfig,
    WorkerConfig,
)

__all__ = [
    "AuthConfig",
    "AzureBlobStorageConfig",
    "CalendarExtractorConfig",
    "Config",
    "ConfigError",
    "ContactsExtractorConfig",
    "ConvertersConfig",
    "DirectoryExtractorConfig",
    "EmailExtractorConfig",
    "ExplicitChannel",
    "ExtractionConfig",
    "ExtractorsConfig",
    "GraphConfig",
    "LocalStorageConfig",
    "MailboxConfig",
    "MediaConfig",
    "OneDriveExtractorConfig",
    "ServiceConfig",
    "SharePointExtractorConfig",
    "StateConfig",
    "StorageConfig",
    "TeamsChannelsExtractorConfig",
    "TeamsChatsExtractorConfig",
    "WebConfig",
    "WorkerConfig",
    "load_config",
]
