"""Config package -- re-exports schema, loader, and errors for convenient imports."""

from m365_brain.config.access import require_section
from m365_brain.config.base import SECTION_MODEL_CONFIG
from m365_brain.config.errors import ConfigError
from m365_brain.config.extractors import (
    EXTRACTOR_NAMES,
    CalendarExtractorConfig,
    ContactsExtractorConfig,
    DirectoryExtractorConfig,
    EmailExtractorConfig,
    ExplicitChannel,
    ExtractorsConfig,
    MailboxConfig,
    OneDriveExtractorConfig,
    SharePointExtractorConfig,
    TeamsChannelsExtractorConfig,
    TeamsChatsExtractorConfig,
)
from m365_brain.config.index import (
    Bm25Weights,
    CatalogConfig,
    FrontmatterConfig,
    IndexConfig,
    IndexRoot,
    IndexSyncConfig,
    ObservationConfig,
    RelationConfig,
    SearchConfig,
    SnippetConfig,
    SqliteIndexConfig,
    VectorConfig,
)
from m365_brain.config.loader import load_config
from m365_brain.config.ops import (
    InteractionSourceConfig,
    LinkResolutionConfig,
    OpsConfig,
    PartySelector,
    TierLevelConfig,
    TiersConfig,
    TierWriteBackConfig,
    TimestampSelector,
    TriageConfig,
    TriageFieldsConfig,
)
from m365_brain.config.outbox import (
    EmailOutboxConfig,
    EmailSignatureConfig,
    OutboxDefinitionConfig,
    OutboxesConfig,
    ReconcileConfig,
    Tier,
)
from m365_brain.config.runtime import (
    HooksConfig,
    M365Config,
    ManifestConfig,
    UploadConfig,
    is_hook_spec,
)
from m365_brain.config.schema import (
    AuthConfig,
    AuthProfileConfig,
    AzureBlobStorageConfig,
    Config,
    ConvertersConfig,
    ExtractionConfig,
    GraphConfig,
    LocalStorageConfig,
    MediaConfig,
    ServiceConfig,
    StorageConfig,
    WebConfig,
    WorkerConfig,
)
from m365_brain.config.vault import VaultConfig, VaultFilenames, VaultLayout

__all__ = [
    "EXTRACTOR_NAMES",
    "SECTION_MODEL_CONFIG",
    "AuthConfig",
    "AuthProfileConfig",
    "AzureBlobStorageConfig",
    "Bm25Weights",
    "CalendarExtractorConfig",
    "CatalogConfig",
    "Config",
    "ConfigError",
    "ContactsExtractorConfig",
    "ConvertersConfig",
    "DirectoryExtractorConfig",
    "EmailExtractorConfig",
    "EmailOutboxConfig",
    "EmailSignatureConfig",
    "ExplicitChannel",
    "ExtractionConfig",
    "ExtractorsConfig",
    "FrontmatterConfig",
    "GraphConfig",
    "HooksConfig",
    "IndexConfig",
    "IndexRoot",
    "IndexSyncConfig",
    "InteractionSourceConfig",
    "LinkResolutionConfig",
    "LocalStorageConfig",
    "M365Config",
    "MailboxConfig",
    "ManifestConfig",
    "MediaConfig",
    "ObservationConfig",
    "OneDriveExtractorConfig",
    "OpsConfig",
    "OutboxDefinitionConfig",
    "OutboxesConfig",
    "PartySelector",
    "ReconcileConfig",
    "RelationConfig",
    "SearchConfig",
    "ServiceConfig",
    "SharePointExtractorConfig",
    "SnippetConfig",
    "SqliteIndexConfig",
    "StorageConfig",
    "TeamsChannelsExtractorConfig",
    "TeamsChatsExtractorConfig",
    "Tier",
    "TierLevelConfig",
    "TierWriteBackConfig",
    "TiersConfig",
    "TimestampSelector",
    "TriageConfig",
    "TriageFieldsConfig",
    "UploadConfig",
    "VaultConfig",
    "VaultFilenames",
    "VaultLayout",
    "VectorConfig",
    "WebConfig",
    "WorkerConfig",
    "is_hook_spec",
    "load_config",
    "require_section",
]
