#!/usr/bin/env bash
# Idempotent Azure infrastructure deployment for m365-extract.
#
# What it does:
#   1. Checks that az CLI is logged in
#   2. Creates the resource group if it doesn't exist
#   3. Deploys Bicep template (idempotent — ARM deployments are declarative)
#   4. Retrieves the storage account connection string
#   5. Writes .env.{env} with the connection string
#
# Usage:
#   bash scripts/deploy-infra.sh dev          # deploy dev infra (Standard_LRS)
#   bash scripts/deploy-infra.sh prod         # deploy prod infra (Standard_GRS)
#   bash scripts/deploy-infra.sh dev --dry-run  # validate without deploying
#
# Safe to re-run at any time — all operations are idempotent.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# -- Parse arguments ----------------------------------------------------------

ENV=""
DRY_RUN=false

for arg in "$@"; do
    case "$arg" in
        dev|prod|test) ENV="$arg" ;;
        --dry-run) DRY_RUN=true ;;
        *) echo "Unknown argument: $arg"; echo "Usage: $0 <dev|prod|test> [--dry-run]"; exit 1 ;;
    esac
done

if [ -z "$ENV" ]; then
    echo "Usage: $0 <dev|prod|test> [--dry-run]"
    exit 1
fi

LOCATION="switzerlandnorth"
RESOURCE_GROUP="rg-m365-extract-${ENV}"
PARAMS_FILE="infra/params.${ENV}.bicepparam"
TEMPLATE_FILE="infra/main.bicep"

# -- Colors -------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
fail()  { echo -e "${RED}[FAIL]${NC} $*"; exit 1; }

# -- 1. Check prerequisites ---------------------------------------------------

command -v az >/dev/null 2>&1 || fail "az CLI not found. Install: https://learn.microsoft.com/cli/azure/install-azure-cli"
info "az CLI is available"

# Check login status
if ! az account show >/dev/null 2>&1; then
    fail "Not logged in to Azure. Run: az login"
fi
ACCOUNT_NAME=$(az account show --query name -o tsv)
SUBSCRIPTION_ID=$(az account show --query id -o tsv)
info "Logged in to Azure: $ACCOUNT_NAME ($SUBSCRIPTION_ID)"

# Check template + params files exist
[ -f "$TEMPLATE_FILE" ] || fail "Bicep template not found: $TEMPLATE_FILE"
[ -f "$PARAMS_FILE" ] || fail "Parameter file not found: $PARAMS_FILE"
info "Bicep template and params file found"

# -- 2. Dry run (validate only) -----------------------------------------------

if [ "$DRY_RUN" = true ]; then
    echo ""
    echo "Validating deployment (dry run)..."

    # Ensure resource group exists for validation
    if ! az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1; then
        echo "  Resource group '$RESOURCE_GROUP' does not exist — creating for validation..."
        az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none
    fi

    az deployment group validate \
        --resource-group "$RESOURCE_GROUP" \
        --template-file "$TEMPLATE_FILE" \
        --parameters "$PARAMS_FILE" \
        --output table

    info "Validation passed (no resources deployed)"
    exit 0
fi

# -- 3. Create resource group (idempotent) ------------------------------------

echo ""
echo "Ensuring resource group '$RESOURCE_GROUP' exists..."

if az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1; then
    info "Resource group '$RESOURCE_GROUP' already exists"
else
    az group create \
        --name "$RESOURCE_GROUP" \
        --location "$LOCATION" \
        --output none
    info "Created resource group '$RESOURCE_GROUP' in $LOCATION"
fi

# -- 4. Deploy Bicep template (idempotent) ------------------------------------

echo ""
echo "Deploying Bicep template to '$RESOURCE_GROUP'..."

DEPLOY_OUTPUT=$(az deployment group create \
    --resource-group "$RESOURCE_GROUP" \
    --template-file "$TEMPLATE_FILE" \
    --parameters "$PARAMS_FILE" \
    --output json)

STORAGE_ACCOUNT=$(echo "$DEPLOY_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['storageAccountName']['value'])")
CONTAINER_NAME=$(echo "$DEPLOY_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['containerName']['value'])")

info "Deployed: storage=$STORAGE_ACCOUNT container=$CONTAINER_NAME"

# -- 5. Retrieve connection string ---------------------------------------------

echo ""
echo "Retrieving connection string..."

CONNECTION_STRING=$(az storage account show-connection-string \
    --name "$STORAGE_ACCOUNT" \
    --resource-group "$RESOURCE_GROUP" \
    --output tsv)

info "Connection string retrieved"

# -- 6. Write .env.{env} file -------------------------------------------------

ENV_FILE="$PROJECT_DIR/.env.${ENV}"

cat > "$ENV_FILE" << ENVEOF
# Auto-generated by deploy-infra.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Resource group: $RESOURCE_GROUP
# Storage account: $STORAGE_ACCOUNT
AZURE_STORAGE_CONNECTION_STRING=${CONNECTION_STRING}
AZURE_STORAGE_CONTAINER=${CONTAINER_NAME}
AZURE_STORAGE_PREFIX=${ENV}/
ENVEOF

info "Written $ENV_FILE"

# -- Done ---------------------------------------------------------------------

echo ""
echo -e "${GREEN}Infrastructure deployed successfully.${NC}"
echo ""
echo "Next steps:"
echo "  # Sync to Azure ($ENV):"
echo "  source .env.${ENV}"
echo "  pixi run m365-extract --config config.azure.yaml sync --once --extractors email"
echo ""
echo "  # View blobs:"
echo "  az storage blob list --account-name $STORAGE_ACCOUNT --container-name $CONTAINER_NAME --output table --auth-mode login"
